### ISSUE TITLE
to install the theme

### ISSUE THREAD

**Issue by c-z-chen** [jsmith/vuepress-theme-terminal#3]
没有 `yarn add` 或类似东西么？

**Comment by jsmith** [comment]
You can install this library using:

```
npm i vuepress-theme-terminal
```

or
```
yarn add vuepress-theme-terminal
```

Let me know if you run into any issues!

**Comment by c-z-chen** [comment]
I'm sorry that was a stupid question.. forgot to close.
(I literally thought you are Chinese after seeing the other issue so I used Chinese (\~_~;))

**Comment by c-z-chen** [comment]
Wait.. I am publishing it using Vercel and it succeed, this is the log:
```
20:34:59.907  	Installing build runtime...
20:35:00.323  	Build runtime installed: 415.704ms
20:35:00.724  	Looking up build cache...
20:35:00.773  	Build cache not found
20:35:01.171  	Installing dependencies...
20:35:24.464  	> yorkie@2.0.0 install /vercel/workpath0/node_modules/yorkie
20:35:24.464  	> node bin/install.js
20:35:24.535  	CI detected, skipping Git hooks installation
20:35:26.617  	npm WARN linkifyjs@2.1.9 requires a peer of jquery@>= 1.11.0 but none is installed. You must install peer dependencies yourself.
20:35:26.622  	npm WARN linkifyjs@2.1.9 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
20:35:26.630  	npm WARN linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
20:35:26.635  	npm WARN vuepress-theme-terminal@1.1.8 No repository field.
20:35:26.640  	npm WARN vuepress-theme-terminal@1.1.8 No license field.
20:35:26.647  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
20:35:26.647  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
20:35:26.654  	added 1917 packages from 895 contributors in 25.046s
20:35:27.634  	11 packages are looking for funding
20:35:27.634  	  run `npm fund` for details
20:35:28.066  	> vuepress-theme-terminal@1.1.8 build /vercel/workpath0
20:35:28.066  	> vuepress build demo
20:35:28.504  	 WAIT  Extracting site metadata...
20:35:29.647  	[12:35:29 PM] Compiling Client
20:35:29.665  	[12:35:29 PM] Compiling Server
20:35:32.763  	[12:35:32 PM] Compiled Server in 3s
20:35:35.607  	[12:35:35 PM] Compiled Client in 6s
20:35:35.635  	 WAIT  Rendering static HTML...
20:35:35.659  	[2K[1GRendering page: /[2K[1GRendering page: /404.html[2K[1G
20:35:35.659  	 WAIT  Generating service worker...
20:35:35.773  	 DONE  Success! Generated static files in docs.
20:35:36.115  	Uploading build outputs...
20:35:38.950  	Build completed. Populating build cache...
20:35:49.844  	Uploading build cache [28.83 MB]...
20:35:50.456  	Build cache uploaded: 612.650ms
20:35:50.468  	Done with "package.json"
```

but the [webpage](https://portfolio.knowscount.vercel.app) does not show up quite right – it's blank.

---

for the build command part I wrote 
```
ln -s $(pwd) $(pwd)/node_modules/vuepress-theme-terminal && npm run build
```
and the output folder
```
docs
```

what is wrong?

**Comment by c-z-chen** [comment]
there is an error log in console tho:
```
Did not parse stylesheet at 'https://portfolio.knowscount.vercel.app/vuepress-theme-terminal/assets/css/0.styles.ccaed14a.css' because non CSS MIME types are not allowed in strict mode.
app.883620bf.js:1
```

perhaps this is the problem.

---

the `docs` directory doesn't work right too when I put it onto my server, yet it works absolutely fine in `dev` mode

---

@jsmith

**Comment by jsmith** [comment]
> (I literally thought you are Chinese after seeing the other issue so I used Chinese (~_~;))

Sorry haha that was my fault! I decided to translate my answer since the question was posed in Chinese.

Anyway, that error is likely causing the screen to be blank but I'm not sure why you're getting that error. Is [this](https://github.com/KnowsCount/portfolio) the repository that you're trying to deploy?

Also, there is no need to symlink using `ln -s $(pwd) $(pwd)/node_modules/vuepress-theme-terminal`. That command was just for developing the library itself!

**Comment by c-z-chen** [comment]
yes [it](https://github.com/KnowsCount/portfolio) indeed is exactly the repo I've been talking about! 

> Also, there is no need to symlink using ln -s $(pwd) $(pwd)/node_modules/vuepress-theme-terminal. That command was just for developing the library itself!

but if I run it without this line (`ln -s $(pwd) $(pwd)/node_modules/vuepress-theme-terminal`), the deployment fails...
Hold on a sec and I will post you the log...

**Comment by c-z-chen** [comment]
the log lies herewith:
```
21:37:21 | Cloning github.com/KnowsCount/portfolio (Branch: master, Commit: 7f075d6)
21:37:21 | Cloning completed in 741ms
21:37:21 | Analyzing source code...
21:37:24 | Installing build runtime...
21:37:24 | Build runtime installed: 477.330ms
21:37:25 | Looking up build cache...
21:37:25 | Build cache not found
21:37:25 | Installing dependencies...
21:37:58 | > yorkie@2.0.0 install /vercel/workpath0/node_modules/yorkie
21:37:58 | > node bin/install.js
21:37:58 | CI detected, skipping Git hooks installation
21:38:01 | npm WARN linkifyjs@2.1.9 requires a peer of jquery@>= 1.11.0 but none is installed. You must install peer dependencies yourself.
21:38:01 | npm WARN linkifyjs@2.1.9 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
21:38:01 | npm WARN linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
21:38:01 | npm WARN vuepress-theme-terminal@1.1.8 No repository field.
21:38:01 | npm WARN vuepress-theme-terminal@1.1.8 No license field.
21:38:01 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
21:38:01 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
21:38:01 | added 1917 packages from 895 contributors in 35.26s
21:38:03 | 11 packages are looking for funding
21:38:03 | run `npm fund` for details
21:38:03 | > vuepress-theme-terminal@1.1.8 build /vercel/workpath0
21:38:03 | > vuepress build demo
21:38:04 | WAIT  Extracting site metadata...
21:38:04 | Error: [vuepress] Failed to load custom theme "terminal". File vuepress-theme-terminal/Layout.vue does not exist.
21:38:04 | at resolveOptions (/vercel/workpath0/node_modules/vuepress/lib/prepare/resolveOptions.js:69:15)
21:38:04 | at prepare (/vercel/workpath0/node_modules/vuepress/lib/prepare/index.js:11:25)
21:38:04 | at build (/vercel/workpath0/node_modules/vuepress/lib/build.js:19:25)
21:38:04 | at /vercel/workpath0/node_modules/vuepress/bin/vuepress.js:105:12
21:38:04 | at Command.<anonymous> (/vercel/workpath0/node_modules/vuepress/bin/vuepress.js:42:23)
21:38:04 | at Command.listener (/vercel/workpath0/node_modules/commander/index.js:315:8)
21:38:04 | at Command.emit (events.js:314:20)
21:38:04 | at Command.parseArgs (/vercel/workpath0/node_modules/commander/index.js:651:12)
21:38:04 | at Command.parse (/vercel/workpath0/node_modules/commander/index.js:474:21)
21:38:04 | at Object.<anonymous> (/vercel/workpath0/node_modules/vuepress/bin/vuepress.js:97:9)
21:38:04 | npm ERR! code ELIFECYCLE
21:38:04 | npm ERR! errno 1
21:38:04 | npm ERR! vuepress-theme-terminal@1.1.8 build: `vuepress build demo`
21:38:04 | npm ERR! Exit status 1
21:38:04 | npm ERR!
21:38:04 | npm ERR! Failed at the vuepress-theme-terminal@1.1.8 build script.
21:38:04 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
21:38:04 | npm ERR! A complete log of this run can be found in:
21:38:04 | npm ERR!     /vercel/.npm/_logs/2020-11-30T13_38_04_187Z-debug.log
21:38:04 | Error: Command "npm run build" exited with 1
21:38:05 | Done with "package.json"
```

---

The reason why I added the line is because of this line:
```
Error: [vuepress] Failed to load custom theme "terminal". File vuepress-theme-terminal/Layout.vue does not exist.
```

---

Sorry to interrupt all this time and thank you so much for your time! (●°u°●)​ 」

**Comment by jsmith** [comment]
No problem! Let me take a look and I'll get back to you.

**Comment by jsmith** [comment]
Totally forgot to look into this. I'll take a look tomorrow morning. Sorry about the dealy!

**Comment by jsmith** [comment]
Ohh I see that you copied my repo rather than installing it using npm (that's the reason that you need to symlink the root of the repository to `node_modules/vuepress-theme-terminal`). Anyway, how you have it now works fine 👍 

Anyway, to fix your issue, set the `config.json` `base` property to `"/"` :)

**Comment by jsmith** [comment]
Like this:

```
/*
 * @Description: 编辑。
 * @Date: 2020-03-19 09:00:26
 * @Author: KnowsCount
 * @Github: https://github.com/KnowsCount/NKCS-Storage
 * @LastEditTime: 2020-11-30 19:58:49
 * @FilePath: /vuepress-theme-terminal-master/demo/.vuepress/config.js
 */
module.exports = {
	dest: "docs",
	theme: "terminal",
	serviceWorker: true,
	title: "KcNotes",
	base: "/",
};
```

**Comment by c-z-chen** [comment]
ok, thanks! ┏ (^ω^)=
